agents:

  age_groups:
    GenZ:
      ratio: 0.2494
      digital_exposure: 0.48

    Millennial:
      ratio: 0.3344
      digital_exposure: 0.40

    GenX:
      ratio: 0.2705
      digital_exposure: 0.32

    Boomer:
      ratio: 0.1308
      digital_exposure: 0.22

    PreBoomer:
      ratio: 0.0149
      digital_exposure: 0.12


  education_levels:
    PrimaryAndLower:
      ratio: 0.238
      cognitive_complexity: 0.30
      issue_based_reasoning: cognitive_complexity 
      authority_deference: 1 - cognitive_complexity

    SecondaryLevel:
      ratio: 0.61
      cognitive_complexity: 0.50
      issue_based_reasoning: cognitive_complexity 
      authority_deference: 1 - cognitive_complexity

    University:
      ratio: 0.148
      cognitive_complexity: 0.75
      issue_based_reasoning: cognitive_complexity 
      authority_deference: 1 - cognitive_complexity


  income_levels:
    Poor:
      ratio: 0.233
      economic_anxiety: 0.78
      welfare_salience: 0.80
      status_quo_bias: 0.25

    Vulnerable:
      ratio: 0.536
      economic_anxiety: 0.65
      welfare_salience: 0.68
      status_quo_bias: 0.40

    MiddleUpper:
      ratio: 0.139
      economic_anxiety: 0.35
      welfare_salience: 0.42
      status_quo_bias: 0.65

